apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextexplorer
  namespace: {{ .Release.Name }}
  labels:
    app: nextexplorer
spec:
  serviceName: nextexplorer
  replicas: 1
  selector:
    matchLabels:
      app: nextexplorer
  template:
    metadata:
      labels:
        app: nextexplorer
        domain: apps
    spec:
      containers:
        - name: nextexplorer
          image: 'nxzai/explorer:{{ .Chart.AppVersion }}'
          imagePullPolicy: IfNotPresent
          # need to run as root since the mounted files are root
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          env:
            - name: NODE_ENV
              value: production
            - name: PUBLIC_URL
              value: http://explorer.local
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: config
                  key: session_secret
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /cache
              name: cache-volume
            {{- range .Values.homeCloud.disks }}
            - mountPath: {{ printf "/mnt/%s" .name }}
              name: {{ .name }}
            {{- end }}
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: cache-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cache
        {{- range .Values.homeCloud.disks }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
