kind: ConfigMap
apiVersion: v1
metadata:
  name: immich
  namespace: {{ .Release.Name }}
data:
  immich.json: |
    {
      "newVersionCheck": {
        "enabled": false
      },
      "server": {
        "externalDomain": "http://photos.local"
      },
      "machineLearning": {
        "urls": ["http://machine-learning:3003"]
      }
    }