apiVersion: v2
name: nextexplorer
description: A modern, self-hosted file explorer with secure access control and a polished UX.
icon: https://raw.githubusercontent.com/nxzai/NextExplorer/refs/heads/main/docs/public/images/logo.png
type: application
version: 0.0.1
appVersion: v2.2.6
home: https://explorer.nxz.ai/
sources:
  - https://github.com/nxzai/NextExplorer
annotations:
  displayName: Explorer
  status: alpha
