apiVersion: v2
name: memos
description: A privacy-first, lightweight note-taking service. Easily capture and share your great thoughts.
icon: https://avatars.githubusercontent.com/u/95764151?s=48&v=4
type: application
version: 0.0.6
appVersion: 0.23.1
home: https://www.usememos.com/
sources:
  - https://github.com/usememos/memos
dependencies:
  - name: postgres
    version: 0.x.x
    repository: https://apps.home-cloud.io
    condition: homeCloud.dependencies.postgres.install
annotations:
  displayName: Memos
  status: stable
