apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      affinity:
        nodeAffinity: {{ toYaml .Values.homeCloud.nodeAffinity | nindent 12 }}
      containers:
        - name: home-assistant
          image: 'homeassistant/home-assistant:{{ .Chart.AppVersion }}'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - 'echo "db_url: $(cat /etc/secrets/postgres/uri)" > /config/secrets.yaml'
          volumeMounts:
            - name: config
              mountPath: /config
            - name: configmap
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: postgres-secrets
              mountPath: /etc/secrets/postgres
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: configmap
          configMap:
            name: home-assistant
        - name: postgres-secrets
          secret:
            secretName: postgres-homeassistant
