apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
  namespace: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
  selector:
    app: home-assistant
