replicaCount: 1

homeCloud:
  routes:
    - name: homeassistant
      service:
        name: ha
        port: 8123

  databases:
    - name: homeassistant
      type: postgres

  persistence:
    - name: config
      size: 64Gi
