replicaCount: 1

homeCloud:
  routes:
    - name: home-assistant
      service:
        name: home-assistant
        port: 8123

  databases:
    # NOTE: postgres doesn't allow hyphens in database names
    - name: homeassistant
      type: postgres

  persistence:
    - name: config
      size: 64Gi
