apiVersion: v2
name: searxng
description: SearXNG is a free internet metasearch engine which aggregates results from various search services and databases. 
icon: https://avatars.githubusercontent.com/u/80454229?s=48&v=4
type: application
version: 2026.9.12-d4f00d15d
appVersion: 2026.9.12-d4f00d15d
home: https://docs.searxng.org/
sources:
  - https://github.com/searxng/searxng
annotations:
  displayName: SearXNG
  status: stable
