# NOTE: for internal operator use only
# disks:
#   - name: alice
#   - name: bob

homeCloud:
  routes:
    - name: files
      service:
        name: filebrowser
        port: 80

  # for the database
  persistence:
    - name: config
      size: 1Gi
